### ISSUE TITLE
"Enable Fabric8 Analytic" DefaultToolItem button has Label "Exit".

### ISSUE THREAD

**Issue by vprusa** [fabric8-analytics/fabric8-analytics-devstudio-plugin#109]
"Enable Fabric8 Analytic" DefaultToolItem button has Text correct but Label is "Exit".

Reproduce:
- Hover the button for few seconds.

**Comment by GeetikaBatra** [comment]
Fixed https://github.com/fabric8-analytics/fabric8-analytics-devstudio-plugin/pull/110
