### ISSUE TITLE
Devstudio Production Ready

### ISSUE THREAD

**Issue by GeetikaBatra** [fabric8-analytics/fabric8-analytics-devstudio-plugin#11]
- [x]  Create and update site for the plugin
- [x] Trigger analyses on Jenkins
- [x]  Upload the plugin on download.jboss.org

**Comment by GeetikaBatra** [comment]
- [ ] Change the triggering point of stack analyses from manifest file to entire project.

- [ ] Bug- Token if changed from preference is not updated in stack analyses

- [ ] Bug- unhandled event loop exception when clicked stack analyses twice

- [ ] Get the code reviewed and refactored accordingly

- [ ]

**Comment by GeetikaBatra** [comment]
- [ ] Unit Tests

- [ ] Integration Tests

**Comment by GeetikaBatra** [comment]
- [ ] Add support of multiple manifest files

**Comment by GeetikaBatra** [comment]
**BACK LOG**

- [ ] Research on how lsp4e plugin can be embedded into bayesian plugin, so that there is no need of installing it explicitely

**Comment by nickboldt** [comment]
Please don't embed plugins in plugins. Just depend on them. It's cleaner and doesn't bloat the user's installation.

**Comment by nickboldt** [comment]
If this issue is resolved, perhaps it's time to bump your plugins and features up to version 1.0.0? 0.0.1 suggests quality = Alpha at best.
