### ISSUE TITLE
Cannot run stack analyses

### ISSUE THREAD

**Issue by ljelinkova** [fabric8-analytics/fabric8-analytics-devstudio-plugin#118]
Cannot run stack analyses because the server returns code 503 (service unavailable).

**Comment by GeetikaBatra** [comment]
https://github.com/fabric8-analytics/fabric8-analytics-devstudio-plugin/pull/110
This should fix it. Currently in process of rebase.

**Comment by GeetikaBatra** [comment]
Fixed https://github.com/fabric8-analytics/fabric8-analytics-devstudio-plugin/pull/110
