### ISSUE TITLE
Run osio login request just once for all projects and pom files in workspace on devstudio start

### ISSUE THREAD

**Issue by vprusa** [fabric8-analytics/fabric8-analytics-devstudio-plugin#119]
In case i have 5 project in workspace and im not logged into OSIO and start Devstudio it opens 5 Dialogs "Login to Openshift.io" .. I am not sure if it opens OSIO Login dialog per project or per pom in project.

**Comment by GeetikaBatra** [comment]
This is fixed as login workflow has changes.
