### ISSUE TITLE
Analyses returns http return code 404

### ISSUE THREAD

**Issue by ljelinkova** [fabric8-analytics/fabric8-analytics-devstudio-plugin#126]
No analyses can be run at them moment since the server returns 404 code.

**Comment by GeetikaBatra** [comment]
3scale pods are down, as there is a change going on. Analyses would work once the pods are up.

**Comment by GeetikaBatra** [comment]
Covered by https://github.com/fabric8-analytics/fabric8-analytics-devstudio-plugin/pull/140
