### ISSUE TITLE
Maven effective pom files are stored into the filesystem

### ISSUE THREAD

**Issue by ljelinkova** [fabric8-analytics/fabric8-analytics-devstudio-plugin#127]
The maven effective pom files are stored into the target folder of the project. I think this is
a) wrong place since target directory is an output directory of the project not a place where Eclipse plugins should  store their temporary files
b) it is not necessary since such file could be stored just in memory to send it to the server

**Comment by GeetikaBatra** [comment]
Handled by https://github.com/fabric8-analytics/fabric8-analytics-devstudio-plugin/pull/142
Closing the issue.
