### ISSUE TITLE
Issues with AnalysesJobHandler

### ISSUE THREAD

**Issue by ljelinkova** [fabric8-analytics/fabric8-analytics-devstudio-plugin#128]
There are several issues with this class

- it seems that the effective pom files are created every time this method is called and that also the server side is called every time. This method is called recursively so as the result the server side is bombed by the requests

- the temporary directory is not deleted in case same exception occurs

- it uses static reference to EditorComposite - in case 2 different pom files request the analyses, the results could be mixed up

**Comment by GeetikaBatra** [comment]
@ljelinkova, what else can be the possible solution to handle effective pom files?
We can work on not storing the files in any temporary folder.
Will, make editor composite non static.

**Comment by GeetikaBatra** [comment]
Fixed by https://github.com/fabric8-analytics/fabric8-analytics-devstudio-plugin/pull/140 and https://github.com/fabric8-analytics/fabric8-analytics-devstudio-plugin/pull/139

**Comment by GeetikaBatra** [comment]
For Effective pom file handling refer to this issue https://github.com/fabric8-analytics/fabric8-analytics-devstudio-plugin/issues/141
