### ISSUE TITLE
Stack Analyses not running on installation.

### ISSUE THREAD

**Issue by GeetikaBatra** [fabric8-analytics/fabric8-analytics-devstudio-plugin#133]
For some projects imported, Stack Analyses is not working on installation.

**Comment by sivaavkd** [comment]
<img width="1680" alt="screen shot 2018-01-18 at 4 00 53 pm" src="https://user-images.githubusercontent.com/32661994/35093613-da505266-fc68-11e7-9cab-5cb66acd7d6d.png">
Here is the screenshot right after installing devstudio and plugin.

**Comment by GeetikaBatra** [comment]
Fixed by https://github.com/fabric8-analytics/fabric8-analytics-devstudio-plugin/pull/140
