### ISSUE TITLE
LSP connection provider throws exception when token is null

### ISSUE THREAD

**Issue by rawagner** [fabric8-analytics/fabric8-analytics-devstudio-plugin#146]
https://github.com/fabric8-analytics/fabric8-analytics-devstudio-plugin/blob/master/plugins/com.redhat.fabric8analytics.lsp.eclipse.ui/src/com/redhat/fabric8analytics/lsp/eclipse/ui/Fabric8AnalyticsStreamConnectionProvider.java#L115

the condition should be the opposite -> if(token == null)

**Comment by GeetikaBatra** [comment]
I think we can close this as there it is a checkpoint in order to get refreshed token.

**Comment by rawagner** [comment]
I agree. Closing
