### ISSUE TITLE
Replace all printStackTrace and System.out.println calls with proper logging

### ISSUE THREAD

**Issue by rawagner** [fabric8-analytics/fabric8-analytics-devstudio-plugin#149]
any printStackTrace() should be replaced with logError()

any System.out.println() should be replaced with logInfo(), or removed

**Comment by GeetikaBatra** [comment]
Covered by https://github.com/fabric8-analytics/fabric8-analytics-devstudio-plugin/pull/154

**Comment by rawagner** [comment]
And #157

**Comment by rawagner** [comment]
Both PR's are merged. Closing
