### ISSUE TITLE
Issues with current workflows

### ISSUE THREAD

**Issue by rawagner** [fabric8-analytics/fabric8-analytics-devstudio-plugin#158]
Lets take a look at current workflows and discuss what is ok/not ok.

**1.WORKFLOW - generate stack analysis via project's context menu**
1. create new project, right clik and select "Stack Analyses"
2. I am asked to enable F8A in preferences -> why ? I just manually selected that I want to generate Stack Analyses
3. Well...ok, i go to preferences and enable F8A
4. right click on project and select "Select Analyses"
5. Fail - cannot run analyses because login to openshift.io failed -> I can just click "OK" and nothing happens

**2.WORKFLOW - generate stack analysis via pom.xml editor**
Now lets take a look at generating stack analyses via pom.xml editor
1. open new,clean Workspace
2. create project, open pom.xml, select F8A tab, hit "Generate Stack report"
3. Login window is opened and i should login 

Differences between 1 and 2 workflow
- I am not aksed to enable F8A in preferences (it is actually automatically enabled when i click "Generate Stack report") in 2. workflow
- Login browser is automatically opened in 2. workflow, 1. workflow just gives me a message that osio login failed

**3.WORKFLOW - LSP**
1. open new,clean Workspace
2. enable F8A in preferences
3. create project, open pom.xml
4. a login window is opened - again inconsistent behaviour from the first two
5. in case i close this window, it is opened again a few times
====================================================================

I see no reason to have give an option to disable/enable whole F8A. 
1. Workflow-> there is no reason to check if F8A is enabled/disabled because user manually chose to generate stack analysis
2. Workflow -> again, no reason to check if F8A is enabled/disaled due to user's action
3. Workflow -> this is the only workflow where it makes sense to check if F8A is enabled

therefore I propose to:
1. change Preference option "Fabric8 Analytics" to "Fabric8 Analytics LSP" 
2. remove F8A enablement check from workflow 1 and 2

I also propose to to revamp the login process
1. If a user needs to login, give him an option (ie WORKFLOW no.1, step5 - give user option to login to OSIO )
2. for LSP server, do not automatically open login window - but log and info message that user needs to login in order to use LSP

**Comment by GeetikaBatra** [comment]
Hi @rawagner, can we have a Bluejeans discussion on the above points sometime around tomorrow?

**Comment by rawagner** [comment]
@GeetikaBatra sure. But I have a PTO tomorrow. Can we meet on Monday ?

**Comment by rawagner** [comment]
PR #160 for the issue. Lets talk about it next week

**Comment by rawagner** [comment]
PR merged
