### ISSUE TITLE
F8A Devstudio plugin on Windows 10

### ISSUE THREAD

**Issue by sivaavkd** [fabric8-analytics/fabric8-analytics-devstudio-plugin#164]
The plugin itself works fine, but F8A webpage that should show the results does not work in internal eclipse browser. There is some strange issue with the F8A webpage javascript code & internal eclipse browser.

eclipse internal browser is using InternetExplorer libraries and the webpage is not working in InternetExplorer too.

webpage works in Chrome/Firefox/Edge but does not work in InternetExplorer (thus not working in internal eclipse browser)

cc @rawagner @jyasveer @arunkumars08 @invincibleJai @GeetikaBatra

**Comment by sivaavkd** [comment]
@jyasveer - can you please verify if new stack report is working properly on IE or not ?

**Comment by arunkumars08** [comment]
@sivaavkd We have to test for various versions of IE. Majority uses Edge in Windows 10. Still we need to test for IE.

**Comment by rawagner** [comment]
@arunkumars08 Can you please take a look/fix this asap ? We plan to release the plugin for Devstudio 10.3.0.AM1 which has a code freeze next week (07.02).

**Comment by arunkumars08** [comment]
@jyasveer Could you take a look at this? I am on transit.

**Comment by arunkumars08** [comment]
@rawagner Just wanna highlight that this doesn't involve any changes in Dev
studio plugin extension. It is a separate UI portal which can be updated
incrementally.

**Comment by rawagner** [comment]
@arunkumars08 sure that's why I was looking for help from f8a frontend team as there is nothing I can do from plugin side :) Thanks!

**Comment by jyasveer** [comment]
@rawagner as @arunkumars08 said, this report is totally independent of the dev studio plugin. it is a self hosted website that can be updated incrementally. Again, the stack report portal works in all the modern browsers say it Edge, Chrome and Firefox. If we talk about IE, we have to see what exactly is breaking there

**Comment by rawagner** [comment]
Fixed with https://github.com/fabric8-analytics/fabric8-analytics-stack-report-ui/commit/045d4ea43356ee72b7a0db451705f5dd82accfd6 and https://github.com/openshiftio/saas-analytics/pull/241
