### ISSUE TITLE
Implement token access through an extension point/OSGI service

### ISSUE THREAD

**Issue by jeffmaury** [fabric8-analytics/fabric8-analytics-devstudio-plugin#17]
As of yet, the token is managed through an Eclipse preference which has the following drawbacks:

- security: it should be stored in secured storage as this is a sensitive data
- it forces user to find the token in the OSIO UI and it is a bad UX

As DevStudio/JBossTools team will force as part of the Freesia release train on implementing OSIO login, it would be nice that the LSP plugin get access to the token through an extension point/OSGI service (that will be implemented of course by DevStudio/JBossTools team).
So the behaviour would be:

- if there is an extension point implementation/OSGI service found, call it to get the token
- if not use the current implementation

**Comment by ljelinkova** [comment]
What is the point of keeping the current implementation? Once the OSIO is implemented, why not rely entirely on it?

**Comment by jeffmaury** [comment]
It could be removed but the dependency (org.jboss.tools.openshift.io.core and org.jboss.tools.openshift.io.ui) should be added to the update site so that we can assert the extension point can be found

**Comment by ljelinkova** [comment]
OK, thanks for the reply.

**Comment by GeetikaBatra** [comment]
This has been implemented. Closing this issue https://github.com/fabric8-analytics/fabric8-analytics-devstudio-plugin/commit/b54bc637f98d7b2fd7759e22f77a83dd45ab15d9
