### ISSUE TITLE
Java sources are missing copyright information

### ISSUE THREAD

**Issue by psrna** [fabric8-analytics/fabric8-analytics-devstudio-plugin#19]

**Comment by GeetikaBatra** [comment]
@psrna, Can you point me out the exact copyright information that I can add to the code. Thanks in advance.

**Comment by psrna** [comment]
This is what we have for JBossTools.

https://github.com/jbosstools/jbosstools-base/blob/master/foundation/features/org.jboss.tools.foundation.license.feature/feature.properties

https://github.com/jbosstools/jbosstools-base/blob/master/foundation/features/org.jboss.tools.foundation.license.feature/license.html

**Comment by GeetikaBatra** [comment]
Thanks @psrna , will work on it.

**Comment by nickboldt** [comment]
Is this still an issue, @psrna  ? I see https://github.com/fabric8-analytics/fabric8-analytics-devstudio-plugin/blob/master/features/com.redhat.fabric8analytics.lsp.eclipse.feature/feature.properties has copyright info, and https://github.com/fabric8-analytics/fabric8-analytics-devstudio-plugin/blob/master/features/com.redhat.fabric8analytics.lsp.eclipse.feature/feature.xml contains a ref to that copyright + the jbt license feature.

**Comment by psrna** [comment]
Yes, I think so. In JBossTools we add copyright info into every *.java file. 

e.g. https://github.com/jbosstools/jbosstools-openshift/blob/52ceade1f9d6ece75c752eb120ce4940ea7ce4d2/plugins/org.jboss.tools.openshift.core/src/org/jboss/tools/openshift/core/server/OpenShiftServer.java#L1

In the past we have been told that it is a requirement. But maybe it has changed, @nickboldt ?
