### ISSUE TITLE
Auto wrap token field in preferences

### ISSUE THREAD

**Issue by psrna** [fabric8-analytics/fabric8-analytics-devstudio-plugin#20]
If you reopen preferences with previously stored long token, the token field is not wrapped automatically and grabs the whole screen area.

Screenshot: https://www.dropbox.com/s/f5wzy4xvf1hztbc/Screenshot%202017-09-13%2010.01.09.png?dl=0

**Comment by GeetikaBatra** [comment]
The authentication mechanism has changed entirely, the preference window is out of picture now. I think we can close this now.
