### ISSUE TITLE
Stack Analyses view never stops loading

### ISSUE THREAD

**Issue by psrna** [fabric8-analytics/fabric8-analytics-devstudio-plugin#21]
The view content is loading forever. There should be a reasonable timeout showing the error if it cannot load.

**Comment by GeetikaBatra** [comment]
Stack Analyses takes a little while to load. I think the prod was down when this request was made. Please let me know if we still need to add timeout. Thanks in advance.

**Comment by psrna** [comment]
In my opinion the timeout is still needed. If the prod was down, or something else happend. The view should stop showing the loading progress bar (timeout) and communicate errors accordingly to the user.

**Comment by jeffmaury** [comment]
I also noted that Stack Analyses does not work on Win10. If you copy the URL from the Stack Analyses window to Microsoft Edge you got the same result and looking at the developer tools there's a JS error when loading the view. I think this is blocker for initial release

**Comment by GeetikaBatra** [comment]
@psrna , creating an issue for the same. What should be the standard time for timeout?

@jeffmaury, I think @arunkumars08 and @invincibleJai can help us fix this.

**Comment by invincibleJai** [comment]
Yes @GeetikaBatra  timeout needs to be handled in logic of IDEs extension as from IDE we are making poll for stack analysis to check if result is ready.
In case of call taking more than x amount of time should be timed out or in case or doing poll for y times and still analysis is not complete can give some notification to user.

Arun can help with "Stack Analyses does not work on Win10" , @arunkumars08  pls test portal once in Edge , looks like something is breaking there.

**Comment by GeetikaBatra** [comment]
@jeffmaury, This PR fixes the Microsoft Edge issue. https://github.com/fabric8-analytics/fabric8-analytics-stack-report-ui/pull/36

**Comment by arunkumars08** [comment]
@jeffmaury I have logged an issue regarding the same here - https://github.com/openshiftio/openshift.io/issues/1143

I have made some code changes. Once it is reflected, @GeetikaBatra  can test and update here.

**Comment by GeetikaBatra** [comment]
@arunkumars08, Thanks

**Comment by ljelinkova** [comment]
I've created separate issue for analyses timeout #86. I think this issue can now be closed.

**Comment by GeetikaBatra** [comment]
This is no longer necessary as the loading part is covered by crowd sourcing api.
https://github.com/fabric8-analytics/fabric8-analytics-devstudio-plugin/issues/92
