### ISSUE TITLE
Change the lookup of Maven pom files

### ISSUE THREAD

**Issue by ljelinkova** [fabric8-analytics/fabric8-analytics-devstudio-plugin#28]
While current solution works on small scale projects, it would not work on a large ones (like the whole wildfly project for example). 

There should be a possibility to get the list of maven pom files from the maven plugin.

**Comment by GeetikaBatra** [comment]
Thanks @ljelinkova 
Can you please elaborate it.

**Comment by ljelinkova** [comment]
Well, one problem that can occur is that it is possible to use any file name as maven script and you can then run it like this. 

`` mvn -f <other pom file > ``

So simply looking into all pom.xml files might not be sufficient. 

There could be more issues and it might be a good idea to investigate, if some other plugin, e.g. some m2e plugin can do this task for you.

**Comment by fbricon** [comment]
By default, I'd say do something like:

```java
IWorkspaceRoot root = ResourcesPlugin.getWorkspace().getRoot();
List<IFile> poms = new ArrayList<>();
for (IProject project : root.getProjects()) {
   if (project.isAccessible()) {
     IFile pom = project.getFile("pom.xml");
     if (pom.isAccessible()) {
       poms.add(pom);
     }
  }
}
```
- It should be very fast 
- doesn't depend on the m2e API (so works for projects using mvn eclipse:eclipse)
- should cover 99+% of the use cases

2 caveats:
- is it doesn't find non standard pom.xmls, but not the complexity of looking further is worth it
- it only finds poms at the root of maven projects imported as eclipse projects (which is what m2e API would return anyway). Again, not sure looking further down for poms would be worth it.

**Comment by ljelinkova** [comment]
According to Fred's suggestion only pom.xml files in project root are processed. However, the algorithm was changed to process only selected projects or pom.xml files. 

Fixed by #54.

**Comment by GeetikaBatra** [comment]
Support for multiple manifest file is needed, which might not be covered by this PR. Reopening the issue.

**Comment by fbricon** [comment]
Manifest support is a different requirement, should be dealt as a different issue

**Comment by GeetikaBatra** [comment]
Alright, I will create a new issue for the same.
