### ISSUE TITLE
Use Eclipse's jobs instead of own treads

### ISSUE THREAD

**Issue by ljelinkova** [fabric8-analytics/fabric8-analytics-devstudio-plugin#29]
Examples are available here: http://www.vogella.com/tutorials/EclipseJobs/article.html#eclipse-background-processing

**Comment by GeetikaBatra** [comment]
https://github.com/fabric8-analytics/fabric8-analytics-devstudio-plugin/commit/36c06eb1c91ef8d6bf7b6fe4ed8650b8a8d7c2d1
