### ISSUE TITLE
Remove all .DS_Store files (and add to .gitignore)

### ISSUE THREAD

**Issue by fbricon** [fabric8-analytics/fabric8-analytics-devstudio-plugin#33]
.DS_Store files are macOS specific and generally useless files, please remove them from the git repo

**Comment by GeetikaBatra** [comment]
This was closed with https://github.com/fabric8-analytics/fabric8-analytics-devstudio-plugin/commit/09d039e9d109ba02164faa6b15d2fbb509f6a5a0
