### ISSUE TITLE
Remove fabric8-analytics-lsp-server-test-devstudio from git repo

### ISSUE THREAD

**Issue by fbricon** [fabric8-analytics/fabric8-analytics-devstudio-plugin#35]
fabric8-analytics-lsp-server-test-devstudio is downloaded and installed at build time, it should be removed from the git repo (and added to .gitignore)

**Comment by fbricon** [comment]
Moreover, https://github.com/fabric8-analytics/fabric8-analytics-devstudio-plugin/blob/f82c95751dca9645b5952519d4f25ca971000570/plugins/com.redhat.fabric8analytics.lsp.eclipse/src/com/redhat/fabric8analytics/lsp/eclipse/Fabric8AnalyticsStreamConnectionProvider.java#L45 should be fixed to point to the server/ folder at the root of the plugin.

Make sure the build.properties is configured accordingly

**Comment by GeetikaBatra** [comment]
This is covered in the following PR https://github.com/fabric8-analytics/fabric8-analytics-devstudio-plugin/pull/49
