### ISSUE TITLE
Do not unnecessarily export packages in MANIFEST.MF

### ISSUE THREAD

**Issue by fbricon** [fabric8-analytics/fabric8-analytics-devstudio-plugin#36]
This plugin is not responsible for [exporting](https://github.com/fabric8-analytics/fabric8-analytics-devstudio-plugin/blob/f82c95751dca9645b5952519d4f25ca971000570/plugins/com.redhat.fabric8analytics.lsp.eclipse/META-INF/MANIFEST.MF#L28-L75) http packages to others.
The only candidate for export is `com.redhat.fabric8analytics.lsp.eclipse`, but unless some other plugin actually consumes it, that's unnecessary. Once you add a test plugin, that needs access to com.redhat.fabric8analytics.lsp.eclipse classes, then it might be useful.

TLD;DR : don't export anything

**Comment by ljelinkova** [comment]
This was fixed with #31
