### ISSUE TITLE
Move all internal classes to an *.internal package

### ISSUE THREAD

**Issue by fbricon** [fabric8-analytics/fabric8-analytics-devstudio-plugin#37]
In some conventions, non API classes are usually kept under *.internal packages. It makes accidental public exposure of internal stuff less likely. 
I recommend moving all internal classes to com.redhat.fabric8analytics.lsp.eclipse.internal. Anything that should be considered API can be left in the current package.
Only public packages should be exported in the manifest. See #36

**Comment by ljelinkova** [comment]
Fixed by #78
