### ISSUE TITLE
The URL for displaying analyses

### ISSUE THREAD

**Issue by ljelinkova** [fabric8-analytics/fabric8-analytics-devstudio-plugin#55]
When the analyses is requested, the request is sent to 
https://recommender.api.openshift.io/api/v1/stack-analyses/

However, the results are downloaded from
http://ops-portal-v2-ops-portal-ide.dev.rdu2c.fabric8.io/#/analyze

Is it all right to use this URL or should there be some more "official"?

**Comment by GeetikaBatra** [comment]
@ljelinkova, This is official URL for now. Would this be a blocker in the release, if not, let us settle on this. :)

**Comment by krishnapaparaju** [comment]
These URLs need to be mapped thru 3Scale Gateway, with this URLs would change. 

http://ops-portal-v2-ops-portal-ide.dev.rdu2c.fabric8.io/#/analyze is not the right one as this portal been migrated to production.

cc @GeorgeActon  @samuzzal-choudhury @arunkumars08

**Comment by samuzzal-choudhury** [comment]
@krishnapaparaju you are right. @GeetikaBatra @ljelinkova the official route is being assigned on the production cluster. The service delivery issue https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/649 has got the requested URL name and other related communication.

**Comment by ljelinkova** [comment]
This is the code where URL's are used

https://github.com/fabric8-analytics/fabric8-analytics-devstudio-plugin/blob/master/plugins/com.redhat.fabric8analytics.lsp.eclipse.core/src/com/redhat/fabric8analytics/lsp/eclipse/core/RecommenderAPIProvider.java

So would it work if the line 
`private static final String ANALYSES_REPORT_URL =  "http://fabric8-analytics-stack-report-ui-bayesian-preview.b6ff.rh-idev.openshiftapps.com/#/analyze/";
`
is changed by 
`private static final String ANALYSES_REPORT_URL =  "https://stack-analytics-report.openshift.io/#/analyze/";
`

**Comment by ljelinkova** [comment]
@samuzzal-choudhury It is code freeze for Devstudio today. So it is most likely that the old URL will be left in the code. Is that all right?

http://fabric8-analytics-stack-report-ui-bayesian-preview.b6ff.rh-idev.openshiftapps.com/#/analyze/

**Comment by samuzzal-choudhury** [comment]
@ljelinkova changing the `ANALYSES_REPORT_URL` to `private static final String ANALYSES_REPORT_URL = "https://stack-analytics-report.openshift.io/#/analyze/";` will do.

**Comment by GeetikaBatra** [comment]
@ljelinkova  and @samuzzal-choudhury, the Url was not changed because the latest url had some bugs in the UI which I coordinated to @arunkumars08 yesterday. I was waiting for it to get fixed so that I commit the change once I get approval from him.
