### ISSUE TITLE
Add the fabric8 analytics plugin/feature into JBT and Devstudio.

### ISSUE THREAD

**Issue by geetikabatra** [fabric8-analytics/fabric8-analytics-devstudio-plugin#60]
Need to add fabric8 analytics plugin to JBT and Devstudio update site.

https://github.com/jbosstools/jbosstools-devdoc/blob/master/source/how_to_add_a_plugin_or_feature_to_an_existing_project.adoc#add-a-new-plugin-or-feature-to-jboss-tools
https://github.com/jbosstools/jbosstools-devdoc/blob/master/source/publishing_features_downstream.adoc

**Comment by ljelinkova** [comment]
This is the corresponding Jira on DevStudio side

https://issues.jboss.org/browse/JBIDE-24897

Nick asks for confirmation from Jeff MAURY or Bob Davis. @GeetikaBatra  can you ask them?

**Comment by GeetikaBatra** [comment]
This can be closed now, https://issues.jboss.org/browse/JBIDE-24897
