### ISSUE TITLE
Change the Stack Analyses view to Editor view

### ISSUE THREAD

**Issue by GeetikaBatra** [fabric8-analytics/fabric8-analytics-devstudio-plugin#62]
Currently the stack analyses can be viewed from here.

**Comment by GeetikaBatra** [comment]
A tab can be added to editor view using the ```import org.eclipse.m2e.editor.pom.MavenPomEditor;```. Me and @ljelinkova have been able to add this extension point, but the method ```[addEditorPageExtensions](https://github.com/eclipse/m2e-core/blob/11922879173b8516103e935c574be289bc1cbe9c/org.eclipse.m2e.editor/src/org/eclipse/m2e/editor/pom/MavenPomEditor.java#L399)``` is not public.  So we are unable to call it.

**Comment by ljelinkova** [comment]
To be more precise, we added the following into plugin.xml
`<extension
      point="org.eclipse.m2e.editor.pageFactories">
   <factory
         class="com.redhat.fabric8analytics.lsp.eclipse.ui.Fabric8PomEditorFactory">
   </factory>
</extension>`

And created class

` 
public class Fabric8PomEditorFactory extends MavenPomEditorPageFactory{

	@Override
	public void addPages(MavenPomEditor editor) {
		editor.
	}}
`

But I don't see any method we can actually call on editor to insert the Fabrric8 page.

**Comment by fbricon** [comment]
You can try something like 

```java
import org.eclipse.core.runtime.IProgressMonitor;
import org.eclipse.m2e.core.internal.MavenPluginActivator;
import org.eclipse.m2e.core.project.IMavenProjectChangedListener;
import org.eclipse.m2e.core.project.MavenProjectChangedEvent;
import org.eclipse.m2e.editor.pom.MavenPomEditor;
import org.eclipse.m2e.editor.pom.MavenPomEditorPageFactory;
import org.eclipse.ui.PartInitException;
import org.eclipse.ui.forms.IManagedForm;
import org.eclipse.ui.forms.editor.FormPage;
import org.eclipse.ui.forms.editor.IFormPage;

public class Fabric8PomEditorFactory extends MavenPomEditorPageFactory {

	@Override
	public void addPages(MavenPomEditor pomEditor) {
		IFormPage page = new Fabric8FormPage(pomEditor);
		try {
			pomEditor.addPage(page);
		} catch (PartInitException e) {
			//TODO Log Error properly
			e.printStackTrace();
		}
	}

	private  class Fabric8FormPage extends FormPage implements IMavenProjectChangedListener {

		public Fabric8FormPage(MavenPomEditor pomEditor) {
			super(pomEditor, "fabric8.analysis ", "Fabric8 Analysis");
			
		}
		
		@Override
		protected void createFormContent(IManagedForm managedForm) {
			 MavenPluginActivator.getDefault().getMavenProjectManager().addMavenProjectChangedListener(this);
			 // create content
		}

		@Override
		public void mavenProjectChanged(MavenProjectChangedEvent[] events, IProgressMonitor monitor) {
			//react to Maven project changes
		}
		
		@Override
		public void dispose() {
			MavenPluginActivator.getDefault().getMavenProjectManager().removeMavenProjectChangedListener(this);
			super.dispose();
		}		

	}

}
```

**Comment by GeetikaBatra** [comment]
Covered by https://github.com/fabric8-analytics/fabric8-analytics-devstudio-plugin/pull/101
