### ISSUE TITLE
Add Openshift IO plugins into update site

### ISSUE THREAD

**Issue by ljelinkova** [fabric8-analytics/fabric8-analytics-devstudio-plugin#63]
Since the plugin is now dependent on the Openshift IO plugins, it should be added to the site.

**Comment by ljelinkova** [comment]
@nickboldt Could you please help with this one? Do we need to add openshift plugins into category.xml?

**Comment by GeetikaBatra** [comment]
@ljelinkova, I think dependent update is yet to be pushed. It will be done by 24th as far as i know. @jeffmaury might want to add his inputs here.

**Comment by nickboldt** [comment]
The openshift.io plugins are already in JBoss Tools and Developer Studio. 

Are you saying you want your build to depend on the Openshift site? If so I can provide a PR for that so that your local and Jenkins CI builds can resolve the deps.

**Comment by ljelinkova** [comment]
I just want to make sure that the installation will work once the Fabric8 plugin is added into Central. 

So if I understand it correctly it is enough that the OSIO plugins are on the JBT target platform and no additional work is needed?

**Comment by ljelinkova** [comment]
Actually, PR  #68 needs to be merged first.

**Comment by ljelinkova** [comment]
Sorry, I've just read CAREFULLY what Nick wrote and created the following PR #69.

**Comment by ljelinkova** [comment]
This is done, we can close the issue.
