### ISSUE TITLE
What happens with LSP server when token is changed?

### ISSUE THREAD

**Issue by ljelinkova** [fabric8-analytics/fabric8-analytics-devstudio-plugin#64]
The server asks for token once and then sets an environmental variable with the token key and value. What should happen if the token is changed / expired? Should the LSP server check for the changes? Is there an API for that?

@jeffmaury 
@GeetikaBatra

**Comment by jeffmaury** [comment]
@ljelinkova The API that I defined is designed so that the caller should not cache the token and the provider will perform validation when you call it again. But I think the problem is that the Analytics LSP is written in Typescript and my provider is Java so connecting the two may not be trivial

**Comment by GeetikaBatra** [comment]
We can poll for token check every 24 hours when lsp server is called. This will make sure that the latest token is available in the environment.
Also, we need to handle the case where a user closes the sign in window or does not want to sign in initially, there is no way for the user to find the sign in page again in case he/she later changes his/her mind and want's to sign in again.

**Comment by ljelinkova** [comment]
What if we added checkbox to Fabric8 preference page that would enabled / disabled language server? 

- by default it would be enabled
- if user decided that he does not want to login, the language server would be disabled
- if user decided that he wants the language server to work again, it would enable it and we would request the token from OpenshiftIO plugin

And yes, we will probably need to poll the OpenshiftIO service to see, if something with token has changed. However, I would suggest to check it like every hour. Or maybe this value could be also configurable.

**Comment by GeetikaBatra** [comment]
@ljelinkova, can we add a button on the window panel, which just says authorize or unauthorize. The vs code extension is implemented this way only.

**Comment by ljelinkova** [comment]
The following was implemented in #70
- the LSP server can be started/stopped using Preferences
- the OSIO is polled for token regularly and if changed, the LSP server is restarted

**Comment by ljelinkova** [comment]
Actually, support for 

- the OSIO is polled for token regularly and if changed, the LSP server is restarted

is dropped due to complicated implementation not worth the risk of affecting other parts of DevStudio or user experience
