### ISSUE TITLE
Stack analyses is not displayed - only loading

### ISSUE THREAD

**Issue by ljelinkova** [fabric8-analytics/fabric8-analytics-devstudio-plugin#81]
When I run the stack analyses, I do not get any results only page that says Loading...

**Comment by GeetikaBatra** [comment]
The url to view stack analyses was changed. It no longer says loading.

**Comment by ljelinkova** [comment]
The typical workflow is that the QE verifies these kind of issues. So I am reopening the issue until it is verified by QE. You may also want to create some label to mark issues that need QE verification.
