### ISSUE TITLE
Add some notification to user why Openshift.io login is displayed

### ISSUE THREAD

**Issue by ljelinkova** [fabric8-analytics/fabric8-analytics-devstudio-plugin#83]
When user opens pom.xml file, the OpenShift.io login is displayed immediately. This is quite confusing. User should be informed that the Fabric8 analyses needs to login into OpenShift.io and asked, if he/she wants to log in. 

Note that this will need change of OpenShift.io plugin API.

**Comment by GeetikaBatra** [comment]
I think this is not required now, as user will now have to click on OSIO icon inorder to enable Fabric8 analytics, so no login is displayed on click of pom.xml file.
