### ISSUE TITLE
Add timeout for loading the analyses in StackAnalyses view

### ISSUE THREAD

**Issue by ljelinkova** [fabric8-analytics/fabric8-analytics-devstudio-plugin#86]
The stack analyses view is polling for analyses results but if the production is down, it never stops

**Comment by GeetikaBatra** [comment]
This would also be covered by this https://github.com/fabric8-analytics/fabric8-analytics-devstudio-plugin/issues/92

**Comment by GeetikaBatra** [comment]
Covered by https://github.com/fabric8-analytics/fabric8-analytics-devstudio-plugin/pull/140
