### ISSUE TITLE
LSP server authentification

### ISSUE THREAD

**Issue by ljelinkova** [fabric8-analytics/fabric8-analytics-devstudio-plugin#91]
I'd like to ask about the need of authentication in fabric8 lsp server. Is it necessary to provide the user's token to run the server? Could it be changed to some anonymous mode?

The reason I am asking is that it complicates things quite a lot in Devstudio plugin. 

First of all, the user might not want to login into OSIO at first. But the plugin will ask him to do so on every open of pom file. This would be very annoying so in order to prevent it we set an eclipse preference "Fabric8 analyses enabled" to false. User then needs to go to Eclipse Preferences in order to enable the analyses again and login into OSIO. But would he ever do that? If there was no OSIO login needed the analyses would work right away. 

There are also other areas that will not be covered at all
- user deletes his/her token 
- token is expired

How is this done in Visual studio plugin?

@invincibleJai @GeetikaBatra

**Comment by invincibleJai** [comment]
@ljelinkova as per my understanding Is it necessary to provide the user's token to run the server(LSP) as it needs to consume services of OSIO(f8-analytics) which expects access token

In VSCode plugin , we have a separate flow for Auth where in user needs to explicitly trigger `Authorize OSIO` where in user will be authenticated. Till user din't trigger `Authorize OSIO` he won't be able to consume LSP even if manifest files are open i.e `pom.xml, package.json etc`

CC @samuzzal-choudhury @GeetikaBatra

**Comment by GeetikaBatra** [comment]
@ljelinkova . In visual studio, there is a dedicated button clicking which would trigger the Authorization process. 

I agree wth @invincibleJai, the token should not get expired as it is refreshed on the
authorization side every 24 hours. I had confirmed that with Jeff earlier.

![vscode button](https://user-images.githubusercontent.com/8664238/32937776-d0cd4a90-cb9f-11e7-883a-6f3facb6ef00.png)

**Comment by ljelinkova** [comment]
I like the way you solved login and analyses in VSCode pluign and I think we could make it work in Devstudio the same way. There already is the toggle button for login into OSIO (see picture) 

We would need to change some things on Devstudio side but I think this change would improve the overall user experience with the Fabric8 plugin. So if you'd agreed I can create feature request in Devstudio OSIO to make necessary changes. 

![devstudio-screenshot](https://user-images.githubusercontent.com/2078072/33126535-2aa4f2a0-cf85-11e7-8057-2b9bbecd2d32.png)

**Comment by ljelinkova** [comment]
@GeetikaBatra Any thoughts about changing the devstudio plugin to work similar to VSCode plugin?

**Comment by GeetikaBatra** [comment]
@ljelinkova, definitely. Currently, I am working on 3scale integration. You might want to take this up. :)

**Comment by ljelinkova** [comment]
Thanks, I will.

**Comment by GeetikaBatra** [comment]
<img width="1680" alt="screen shot 2017-12-19 at 1 22 16 am" src="https://user-images.githubusercontent.com/8664238/34125565-a8906532-e45c-11e7-8fe3-68ad9d77e7f7.png">


This is something similar I have implemented. It is a WIP. 
Covered by this PR https://github.com/fabric8-analytics/fabric8-analytics-devstudio-plugin/pull/99

**Comment by GeetikaBatra** [comment]
According to disussion with PM, the authentication needs to be enabled using OSIO icon. On clicking OSIO token, a preference page should come up which contains information about the services that would be enables on logging into OSIO.

**Comment by GeetikaBatra** [comment]
Covered by https://github.com/fabric8-analytics/fabric8-analytics-devstudio-plugin/pull/110
