### ISSUE TITLE
Build is not Windows compatible

### ISSUE THREAD

**Issue by jeffmaury** [fabric8-analytics/fabric8-analytics-devstudio-plugin#98]
Looking at https://github.com/fabric8-analytics/fabric8-analytics-devstudio-plugin/blob/d7520eb76255d8200abdef90c9169b9a92831b52/plugins/com.redhat.fabric8analytics.lsp.eclipse.ui/pom.xml#L33 , it is not Windows compatible. There is a Maven plugin for downloading stuff and it supports caching so we should stick to it because I'm stuck testing stuff on Windows now

**Comment by GeetikaBatra** [comment]
Using maven plugin to download and unzip the tar file for lsp server gives this error. 

```
org.apache.maven.plugins:maven-antrun-plugin:1.8:run (default) on project com.redhat.fabric8analytics.lsp.eclipse.ui: An Ant BuildException has occured: Error while expanding /Users/gbatra/fabric8/fabric8-analytics-devstudio-plugin/plugins/com.redhat.fabric8analytics.lsp.eclipse.ui/server/ca-lsp-server-0.0.6-SNAPSHOT.tar
[ERROR] java.io.IOException: Error detected parsing the header
[ERROR] around Ant part ...<untar src="server/ca-lsp-server-0.0.6-SNAPSHOT.tar" dest="server"/>... @ 6:71 in /Users/gbatra/fabric8/fabric8-analytics-devstudio-plugin/plugins/com.redhat.fabric8analytics.lsp.eclipse.ui/target/antrun/build-main.xml: Invalid byte 96 at offset 0 in u���S! len=8
[ERROR] -> [Help 1]  
```

This compelled me to create a shell script for the same.
Please suggest a possible solution for the same.
Thanks in advance

**Comment by GeetikaBatra** [comment]
@nickboldt, Can we build the lsp server from the github repository, the way it is done in Vscode. https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/blob/master/fetch_lsp.sh#L4 
Building the lsp server from github repository would exclude the possibility of getting above errors.

**Comment by nickboldt** [comment]
A few options:

Publish the upstream LSP server .tar or .tgz to download.jboss.org, then use ant or maven to fetch/unpack the tar.

Publish the upstream LSP server to JBoss Nexus, then retrieve and unpack the artifact using mojo. This might be the better option. Wdyt?

(I'm on PTO through EOD tomorrow but had some down time to check mail.)

**Comment by GeetikaBatra** [comment]
Can we publish LSP server .zip instead of .tar. Looks like maven plugin while unpacking the .tar thinks that it is a zip and hence throws error.
I have tried compressing the LSP server in .zip format and it works like charm.

**Comment by nickboldt** [comment]
Yes, anything is possible. Zips don't preserve execute permissions though, so you'd need a shell step to `chmod +x` the binary if you need to start the server... Which might not work the same way on all OSes. Maven Mojo's to fetch from nexus and unpack DO know how to untar, so that's still prolly the best option, IMHO.

**Comment by nickboldt** [comment]
This PR will produce a zip as well as a tar:

https://github.com/fabric8-analytics/fabric8-analytics-lsp-server/pull/21

NOTE that the output of unpacking the tar and the zip is slightly different:

https://imagebin.ca/v/3nqQIARJF59p

**Comment by nickboldt** [comment]
Need another commit... https://github.com/fabric8-analytics/fabric8-analytics-lsp-server/pull/22

then once merged, we can trigger this job...

https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/fabric8/job/jbosstools-fabric8analytics-lsp-server_master/build

...  and should end up with a zip here:

http://download.jboss.org/jbosstools/oxygen/snapshots/builds/jbosstools-fabric8analytics-lsp-server_master/latest/

**Comment by nickboldt** [comment]
PR to make build windows friendly:

https://github.com/fabric8-analytics/fabric8-analytics-devstudio-plugin/pull/110

**Comment by GeetikaBatra** [comment]
Fixed by https://github.com/fabric8-analytics/fabric8-analytics-devstudio-plugin/pull/110
